package gym.memberships;

public class MembershipType {
    private int id;
    private String user_role;
    private String type;
    private String description;
    private int duration_in_months;
    private double cost;

    // Constructor for full object
    public MembershipType(int id, String user_role, String type, String description, int duration_in_months, double cost) {
        this.id = id;
        this.user_role = user_role;
        this.type = type;
        this.description = description;
        this.duration_in_months = duration_in_months;
        this.cost = cost;
    }

    // Constructor for new object (id is preset to 0)
    // this is used when creating a new membership type
    // and the id is not known yet (it will be generated by the database)
    public MembershipType(String userRole, String type, String description, int durationInMonths, double cost) {
        this(0, userRole, type, description, durationInMonths, cost);
    }

    // Getters
    public int getId() { return id; }
    public String getUserRole() { return user_role; }
    public String getType() { return type; }
    public String getDescription() { return description; }
    public int getDurationInMonths() { return duration_in_months; }
    public double getCost() { return cost; }

    // Setters
    public void setId(int id) { this.id = id; }

    @Override
    public String toString() {
        return "[" + this.id + ":"+ this.user_role + "] " + this.type + " (" + this.duration_in_months + "m, $" + this.cost + ")";
    }
}
